/** UNN faculties and departments for researcher signup selects. */
export const UNN_FACULTIES: Record<string, readonly string[]> = {
  "Faculty of Agriculture": [
    "Agricultural Economics",
    "Agricultural Extension",
    "Animal Science",
    "Crop Science",
    "Food Science and Technology",
    "Home Science and Management",
    "Nutrition and Dietetics",
    "Soil Science",
  ],
  "Faculty of Arts": [
    "Archaeology and Tourism",
    "English and Literary Studies",
    "Fine and Applied Arts",
    "Foreign Languages and Literature",
    "History and International Studies",
    "Linguistics, Igbo and other Nigerian Languages",
    "Mass Communication",
    "Music",
    "Theatre and Film Studies",
  ],
  "Faculty of Biological Sciences": [
    "Biochemistry",
    "Microbiology",
    "Plant Science and Biotechnology",
    "Zoology and Environmental Biology",
  ],
  "Faculty of Business Administration": [
    "Accountancy",
    "Banking and Finance",
    "Business Management",
    "Marketing",
  ],
  "Faculty of Education": [
    "Adult Education",
    "Arts Education",
    "Computer Education",
    "Educational Foundations",
    "Human Kinetics and Health Education",
    "Library and Information Science",
    "Science Education",
    "Social Science Education",
  ],
  "Faculty of Engineering": [
    "Agricultural and Bioresources Engineering",
    "Biomedical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Electronic Engineering",
    "Mechanical Engineering",
    "Mechatronic Engineering",
    "Metallurgical and Materials Engineering",
  ],
  "Faculty of Environmental Studies": [
    "Architecture",
    "Estate Management",
    "Geoinformatics and Surveying",
    "Urban and Regional Planning",
  ],
  "Faculty of Law": [
    "Commercial and Corporate Law",
    "Customary and Indigenous Law",
    "International and Comparative Law",
    "Jurisprudence and Legal Theory",
    "Private Law",
    "Property Law",
    "Public Law",
  ],
  "Faculty of Pharmaceutical Sciences": [
    "Clinical Pharmacy and Pharmacy Management",
    "Pharmaceutical and Medicinal Chemistry",
    "Pharmaceutical Microbiology and Biotechnology",
    "Pharmaceutical Technology and Industrial Pharmacy",
    "Pharmaceutics",
    "Pharmacognosy and Environmental Medicines",
    "Pharmacology and Toxicology",
  ],
  "Faculty of Physical Sciences": [
    "Computer Science",
    "Geology",
    "Mathematics",
    "Physics and Astronomy",
    "Pure and Industrial Chemistry",
    "Statistics",
  ],
  "Faculty of the Social Sciences": [
    "Economics",
    "Geography",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Public Administration and Local Government",
    "Religion and Cultural Studies",
    "Social Work",
    "Sociology and Anthropology",
  ],
  "Faculty of Veterinary Medicine": [
    "Veterinary Anatomy",
    "Veterinary Medicine",
    "Veterinary Microbiology and Pathology",
    "Veterinary Obstetrics and Reproductive Diseases",
    "Veterinary Parasitology and Entomology",
    "Veterinary Physiology and Pharmacology",
    "Veterinary Public Health and Preventive Medicine",
    "Veterinary Surgery",
  ],
  "Faculty of Vocational and Technical Education": [
    "Agricultural Education",
    "Business Education",
    "Computer and Robotics Education",
    "Home Economics and Hospitality Management Education",
    "Industrial Technical Education",
  ],
  "Faculty of Basic Medical Sciences": [
    "Anatomy",
    "Medical Biochemistry",
    "Physiology",
  ],
  "Faculty of Clinical Sciences": [
    "Medicine and Surgery",
  ],
  "Faculty of Dentistry": [
    "Child Dental Health",
    "Oral and Maxillofacial Surgery",
    "Preventive Dentistry",
    "Restorative Dentistry",
  ],
  "Faculty of Health Sciences and Technology": [
    "Medical Laboratory Sciences",
    "Medical Radiography and Radiological Sciences",
    "Medical Rehabilitation",
    "Nursing Sciences",
  ],
} as const;

export const UNN_FACULTY_OPTIONS = Object.keys(UNN_FACULTIES);

export function getUnnDepartments(faculty: string): readonly string[] {
  return UNN_FACULTIES[faculty] ?? [];
}
